# Generated by Django 3.2.9 on 2021-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
