# Generated by Django 3.2.9 on 2021-12-12 20:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('asked_date', models.DateTimeField(auto_now_add=True, verbose_name='Asked Date')),
                ('question_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Question Author')),
            ],
            options={
                'ordering': ['-asked_date'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.CharField(max_length=200, null=True, verbose_name='Answer')),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('answer_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ask.questions', verbose_name='Question')),
            ],
            options={
                'ordering': ['-answer_date'],
            },
        ),
    ]
