# Generated by Django 3.2.9 on 2021-12-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_image',
        ),
    ]
