# Generated by Django 3.2.9 on 2021-12-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_remove_questions_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Upload Image'),
        ),
    ]
