# Generated by Django 3.2.9 on 2021-12-12 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_questions_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='answer_content',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='Answer'),
        ),
    ]
