# Generated by Django 3.2.9 on 2021-12-14 18:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ask', '0006_auto_20211214_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
