# Generated by Django 3.2.9 on 2021-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_questions_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
    ]
