# Generated by Django 3.2.9 on 2022-01-04 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ask.questions', verbose_name='Reported Question'),
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.CharField(max_length=255, verbose_name='Message'),
        ),
    ]
