# Generated by Django 3.2.9 on 2022-01-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_auto_20220104_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='question',
        ),
    ]
